services:
  mongodb:
    image: mongo:8.0.20
    restart: unless-stopped
    command:
      - mongod
      - --noauth
      - --bind_ip_all
      - --setParameter
      - diagnosticDataCollectionEnabled=false
    ports:
      - "127.0.0.1:27111:27017"
    volumes:
      - awsops-home-mongo:/data/db

volumes:
  awsops-home-mongo:
